baseURL = "https://boyl.es"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Michael Boyles"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
# Annoying aspect of GitHub pages, don't get much choice in the name 
publishDir = "docs"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Michael Boyles"
author = "Michael Boyles"
description = "London, UK"
profilePicture = "images/portrait-square.png"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/michaelboyles"

[[params.socialIcons]]
icon = "fa-stack-overflow"
title = "StackOverflow"
url = "https://stackoverflow.com/users/1898563/michael"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/boylesm/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "Email"
url = "mailto:michael@boyl.es"

[[params.socialIcons]]
icon = "fa-file"
title = "CV"
url = "https://latexonline.cc/compile?git=https%3A%2F%2Fgithub.com%2Fmichaelboyles%2Fwebsite&target=static%2Fdocs%2Fcv.tex&command=xelatex&trackId=1598651052286"

## Menu items

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

